version: 2

jobs:
  build:
    docker:
    - image: circleci/clojure:lein-2.7.1
    - image: circleci/postgres:9.6-alpine
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      environment:
        POSTGRES_USER: devobs_worker
        POSTGRES_DB: bigger_than_us

    working_directory:    ~/devobs-worker

    environment:
      LEIN_ROOT:          "true"
      JVM_OPTS:           -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies

      - run:
          name: Copy test configuration
          command: |
            cp .lein-env.test.dist .lein-env

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Create database
          command: |
            psql -h 127.0.0.1 -U devobs_worker \
            password='bigger_than_us' \
            -p 5432 -a -q \
            -f ~/devobs-worker/build/create_database.sql && \
            psql -h 127.0.0.1 -U devobs_worker \
            password='bigger_than_us' \
            -p 5432 -a -q \
            -f ~/devobs-worker/build/create_schema.sql

      - run:
          name: Install dependencies
          command: |
            lein deps

      - run:
          name: Run test suite
          command: |
            lein test

      - save_cache:
          key: v1-dependencies-{{ checksum "project.clj" }}
          paths:
          - $HOME/.m2
          - $HOME/.lein
